name: Build Modpacks
on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Download ModPackager
        run: |
          gh release download \
          --repo SoapboxRaceWorld/ModPackager v2.1.0 \
          -p "release_unix.zip" \
          -O /tmp/release_unix.zip
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Extract ModPackager
        run: | 
          unzip -j "/tmp/release_unix.zip" "release_unix/*" \
          -d "./modpackager"

      - name: Check what we got
        run: ls -R

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.101

      - name: Build the thing!
        run: |
          chmod +x ./modpackager/ModPackager && \
          bash ./build.sh

      - name: Check again what we got
        run: ls -R

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: modpack
      #     path: |
      #       ./output/*
      #       !./output/README.md
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      # - name: Upload Modpack
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
      #     asset_path: ./output/*.zip
      #     asset_name: release_unix.zip
      #     asset_content_type: application/zip

      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./output/*